//////////////////////////////////////////////////////
//	Interfaces										//					
//		--- ... 									//
//////////////////////////////////////////////////////

function Interface(_config) : Class(_config) constructor {
	/// @func	Interface(config)
	/// @param	{struct}	config
	/// @return {Interface}	self
	///
	__component = _config.component;
	__owner		= _config.owner;
	__name		= _config.name;
	
	/// @NOTE:	when overriding a method dynamically generated by the interface,
	///			do not declare the new overriding method as static, as the
	///			dynamically generated methods are NOT static.
	///	method_get_index(...) <-- use this to simulate static methods?
	
	__component.get_interface = method(self, function() {
		return self;
	});
	static bind_method		  = function(_name, _method) {
		/// @func	bind_method(name, method)
		/// @param	{string}	name
		/// @param	{method}	method
		/// @return {Interface} self
		///
		__owner[$ __name + "_" + _name] = method(self, _method);
		return self;
	};	
	
	/// Implemented In Class()
	bind_method("get_owner",  function() {
		return __component.get_owner();
	});
	bind_method("get_active", function() {
		return __component.get_active();
	});
	bind_method("get_name",   function() {
		return __component.get_name();
	});
	bind_method("set_owner",  function(_owner) {
		return __component.set_owner(_owner);
	});
	bind_method("set_active", function(_active) {
		return __component.set_active(_active);
	});
	bind_method("set_name",   function(_name) {
		return __component.set_name(_name);
	});
	bind_method("is_active",  function() {
		return __component.is_active();
	});
};
function IStash(_config) : Interface(_config) constructor {
	/// @func	IStash(config)
	/// @param	{struct}	config
	/// @return {Interface}	self
	///
	bind_method("add",					function(_name, _item) {
		return __component.add(_name, _item);
	});
	bind_method("exists",				function(_name) {
		return __component.exists(_name);
	});
	bind_method("remove",				function(_name) {
		return __component.remove(_name);
	});
	bind_method("clear",				function() {
		return __component.clear();
	});
	bind_method("get",					function(_name) {
		return __component.get(_name);
	});
	bind_method("get_names",			function() {
		return __component.get_names();
	});
	bind_method("get_items",			function() {
		return __component.get_items();
	});
	bind_method("get_items_as_array",	function() {
		return __component.get_items_as_array();
	});
	bind_method("get_size",				function() {
		return __component.get_size();
	});
};

